
zuul:
  routes:
    users:
      path: /users/**
      #使用eureka的方式
      #serviceId: eureka-client
      #直接使用url的方式
      url: http://localhost:8080/proxy/

ribbon:
  eureka:
    enabled: false

server:
  port: 8085
management:
  security:
    enabled: false
spring:
  application:
    name: zuul-proxy


