
zuul:
  routes:
    users:
      path: /users/**
      #直接使用url的方式
      url: http://localhost:8080/proxy/
      #使用eureka的方式
      #serviceId: eureka-client

ribbon:
  eureka:
    enabled: false

server:
  port: 8085
management:
  security:
    enabled: false


