server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: source-channel
        input:
          destination: sink-channel
  datasource:
    url:
    username:
    password:
    driver-class-name:



