server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: sink-channel
          contentType: text/plain
  integration:
    poller:
      fixed-delay: 1000

