zuul:
  routes:
    users:
      path: /users/**
      serviceId: eureka-client
      stripPrefix: false
    customers:
      path: /customers/**
      serviceId: customers
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
spring:
  application:
    name: zuul-proxy


