spring.application.name: atlas

eureka.client:
  serviceUrl.defaultZone: http://localhost:8761/eureka/
  register-with-eureka: false
  fetch-registry: false

netflix.atlas.uri: http://localhost:7101/api/v1/publish/